### ISSUE TITLE
Reduce compilation time

### ISSUE THREAD

**Issue by SirWindfield** [SirWindfield/git-cm#2]
The tool is certainly not big and some dependencies take long to compile (`serde`, `console`). Maybe smaller alternatives are available.

Possibilities:
- remove `git2` dependency and call `git` methods through `std::command::Command`.
- remove `serde` and manually use the `toml` crate.

Suggestions welcome ^.^

**Comment by matu3ba** [comment]
Change `clap` to [pico-args](https://github.com/RazrFalcon/pico-args).

**Comment by SirWindfield** [comment]
Uhh, might be a nice change to test out, thanks!

**Comment by eduardocanellas** [comment]
I observed the compilation messages of a `cargo build --release` and it looks like `openssl-sys`, `toml`, `cargo_toml` and `libgit2-sys` are the ones who take the most time to compile... :thinking:

**Comment by eduardocanellas** [comment]
@SirWindfield do we need to have the `ssh` feature from `git2`? If no, could we just get rid of `openssl-sys` and use `default-features = false`?

My compilation times were significantly faster with `git2 = { version = "0.13.17", default-features = false }`

**Comment by SirWindfield** [comment]
I didn't think of that, seems reasonable.

**Comment by SirWindfield** [comment]
> I observed the compilation messages of a `cargo build --release` and it looks like `openssl-sys`, `toml`, `cargo_toml` and `libgit2-sys` are the ones who take the most time to compile... 🤔

We won't be able to drop the `toml` crate as we need some kind of configuration in general and I honestly am not a big fan of YAML or JSON for that. `cargo_toml` is possible in a breaking change as I wanted to move away from having to use the `Cargo.toml` file and use a more general file instead (maybe `.commits.toml` or something like that). 

The type of commits is needed for the other tools I am working on as well (like the changelog generator and the linting tool), so a unified configuration file is happening anyway.
