### ISSUE TITLE
"git cm" fails if invoked from a directory other than git repository root

### ISSUE THREAD

**Issue by maksyms** [SirWindfield/git-cm#31]
I have a project checked out into `/home/maksym/Work/project`. I'm trying to run `git cm` from `/home/maksym/Work/project/rust/src/` directory. The command fails with the following error:

```
thread 'main' panicked at 'Failed to open git repository:
Error { code: -3, klass: 6, message: "could not find repository from \'.\'" }', 
/home/maksym/.cargo/registry/src/github.com-1ecc6299db9ec823/git-cm-0.1.2/src/git.rs:106:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When the same command is run from `/home/maksym/Work/project`, it works flawlessly.

**Comment by SirWindfield** [comment]
You can pass a path as an input value to the command: `git cm ../../`. It's undocumented but it exists :)

**Comment by maksyms** [comment]
True, I discovered that. At the same time, `git commit` does not require that and finds the repository from anywhere in its tree - which is what the fix can do. :)
