### ISSUE TITLE
Repository with no staged changes does still produce a commit hash

### ISSUE THREAD

**Issue by SirWindfield** [SirWindfield/git-cm#34]
Running `git-cm` on a repository with no staged changes does still go through the dialog and prints out the commit hash, but nothing gets added to the repository.
This should be fixed by adding a check that the repository contains staged files and if not, print an error message on stderr and terminate the process.

**Comment by maksyms** [comment]
I need to get the history right, but hopefully this gives the general idea:
https://github.com/maksyms/git-cm/commit/2a67907ef6c775f72f0641e23f1671dba373f4ef

**Comment by SirWindfield** [comment]
Left some comments 👍

**Comment by maksyms** [comment]
Now it should be good. I tested it on a few scenarios - seems to work as expected. Have a look. :-)
