### ISSUE TITLE
Add a `--help` manual entry

### ISSUE THREAD

**Issue by tbarusseau** [SirWindfield/git-cm#4]
`git-cm` doesn't feature a manual entry:

```
$ git cm --help
No manual entry for git-cm
```

**Comment by SirWindfield** [comment]
I didn't add one as there aren't any command line arguments that `git-cm` currently uses. Maybe a basic help + version flag would be appropriate though.

**Comment by tbarusseau** [comment]
> I didn't add one as there aren't any command line arguments that `git-cm` currently uses. Maybe a basic help + version flag would be appropriate though.

Why does adding things after `git cm` creates runtime errors then? Is it because it default to whatever's the default git behavior?

**Comment by SirWindfield** [comment]
It's a "hidden" feature that I actually forgot haha. You can specify a repository with the first arg.

**Comment by tbarusseau** [comment]
It turns out that `git` falls back to `man git-<subcommand>`, in the case of your binary it would be `man git-cm`.

Is it even possible to add anything more than the binary's installation when running `cargo install`?

We probably _could_ generate a manpage at runtime using something like [`man`](https://github.com/rust-cli/man) but I don't think we _should_
