### ISSUE TITLE
CTRL+c make my cursor disappear

### ISSUE THREAD

**Issue by sayanarijit** [SirWindfield/git-cm#40]
Hi

I encountered this issue while trying it out.

[![asciicast](https://asciinema.org/a/g1peD49ChkX3r4ji51dRlcf6d.svg)](https://asciinema.org/a/g1peD49ChkX3r4ji51dRlcf6d)

**Comment by SirWindfield** [comment]
Interesting issue. I think this has to do with an upstream dependency. I'll try opening an issue over there.

**Comment by SirWindfield** [comment]
https://github.com/mitsuhiko/dialoguer/issues/77#issuecomment-669986406

**Comment by SirWindfield** [comment]
Looks like we manually have to add a ctrlc handler.
