### ISSUE TITLE
Add option to open a text editor for the commit's description

### ISSUE THREAD

**Issue by eduardocanellas** [SirWindfield/git-cm#55]
It feels nice to write short stuff like the scope and the header of the commit right from the CLI, but when it comes to a potentially larger text such as the description of the commit, I'd rather write it on a text editor.

Currently, we have the `-e` flag, but this option makes the whole process occur in the text editor, which isn't as convenient as having the CLI questioning you about the smaller fields.

**Comment by SirWindfield** [comment]
I see. Would a last question with a default to `no` be good for this case? If the user presses y, the editor would open with the already generated text in it.

Another option would be to change the current behavior of the `-e` flag and make it open after all questions have been asked.

**Comment by eduardocanellas** [comment]
I like the idea of allowing the user to review/edit the final message.

Both approaches are nice, but I think changing `-e` may be the way to go, initially. IMO, its current behavior makes using the editor too manual, as you have to build each part of the message yourself. Also, changing the behavior of an option rather than the main flow looks less impactful.

It think it would be good for the user experience to add a "do you want to review?" question in the end of the process, though. Currently, the CLI writes the commit right after it got all the information from the user, without allowing its review.

**Comment by SirWindfield** [comment]
> It think it would be good for the user experience to add a "do you want to review?" question in the end of the process, though. Currently, the CLI writes the commit right after it got all the information from the user, without allowing its review.

I didn't add it at the beginning as you could always run `git commit --amend` to basically do the same. I do see why someone might want that though :smile:

**Comment by SirWindfield** [comment]
v0.2.0 has been released. You can either download a pre-built binary or build it from source using crates. homebrew tap is in the works :)

**Comment by SirWindfield** [comment]
Homebrew tap is done as well. You can install it via `brew install sirwindfield/tap/git-cm`. Should work for macOS and Linux as well (if homebrew is installed) :)
