### ISSUE TITLE
Add a human-readable tag to the issue references in the commit

### ISSUE THREAD

**Issue by tbarusseau** [SirWindfield/git-cm#6]
Inserting issue references in a `git cm` prompt results in the references being written without any additional information in the commit message, like so:

```
    ci(CircleCI)!: Renamed main build job
    
    Renamed main build job from `build-base` to `base`
    
    BREAKING CHANGE: The `build-base` job is now named `base`
    
    123
```

In this case, I think it would make more sense to add a `Referenced issues:` before the lone `123`.

**Comment by SirWindfield** [comment]
Sounds reasonable. Maybe something alongside of `Fixes:` or `Closes:`.

**Comment by tbarusseau** [comment]
Especially since if the issue starts with a `#` (like GitHub issues!), the line will be treated as a comment. I'm actually working on a solution for this, taking the `commit_type` into account to actually type `Fixes: ` on `fix`, and `Referenced issues: ` on any other `commit_type`.
