### ISSUE TITLE
Could we have a better line editor?

### ISSUE THREAD

**Issue by eduardocanellas** [SirWindfield/git-cm#60]
While I was using git-cm, I noticed that the line editor which gets our information in each question is very limited. Could we try to find another one which has more features?

## Some Limitations

- We can't use the arrow keys to go back in the text position and delete a typo in the middle or something like that. (#61 should solve it)
- We can't use CTRL + left/right arrow to navigate around the words.
- ...

**Comment by eduardocanellas** [comment]
I did a little digging on the code and dependencies and there's no line editor. Basically `git-cm` calls `dialoguer`, which calls `console`, which calls `stdin().read_line()`...

**Comment by eduardocanellas** [comment]
I guess I found a way to fix the first limitation. There's a way to make dialoguer work with arrow key navigation.

**Comment by eduardocanellas** [comment]
That PR was an easy win, but if we want better line editor I think we would have to move to something like [rustyline](https://github.com/kkawakam/rustyline).

The best solution would be to have `dialoguer` adding it in itself, as requested in [this issue on their repo](https://github.com/mitsuhiko/dialoguer/issues/82).

**Comment by SirWindfield** [comment]
I have a library lying around that I worked on early this year based on `crossterm` (I actually don't really like `console`). It manually implements the most basic readline shortcuts on top of it (like `ctrl-w`). 

The problem with `rustyline` is that lists have to be implemented manually again, as it really only supports a single line. Not a huge deal, but given that I just opted to use `crossterm` and do it myself, as I really like their `queueing` API and I feel that the project is "more" actively maintained, i.e. PRs and issues get resolved faster. I also find the codebase to work with easier. And I already have some PRs in backlog that I'll open once I get time to look over them a last time :)

My library isn't public right now IIRC, it's similarly structured to inquirer-js though, with each prompt type being available as a single crate as well. Makes my potato laptop compile less, which makes me in turn happy haha.

Now thinking about it, I could also just use rusty line for the input prompt and drop the custom code for that prompt :thinking:

**Comment by eduardocanellas** [comment]
That looks nice! It would be great to see a better prompt library. 

It would be good to "cut the tree" in the dependencies. Compilation times look too big for the project. At least it is a motivation to take a break :laughing:

I think the only think that would be "hard" to replace would be the `Select` prompt. The others are pretty straight-forward to change to `rustyline`.
