### ISSUE TITLE
The binary executable depends on source code to run

### ISSUE THREAD

**Issue by NOBLES5E** [SirWindfield/git-cm#64]
For example if I install `git-cm` with `cargo install git-cm`, and then remove the `git-cm` source code from `~/.cargo/registry/src`. Running `git-cm` will give the following error

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)', <home>/.cargo/registry/src/github.com-1ecc6299db9ec823/git-cm-0.2.2/src/main.rs:19:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by SirWindfield** [comment]
I’ve never stumbled upon this. And I am not entirely sure if this is default behavior or a bug on my side. I’ll have to investigate.

**Comment by NOBLES5E** [comment]
Thanks. This makes it hard to package `git-cm` since I should not package source files together with the binary :face_with_head_bandage:

**Comment by SirWindfield** [comment]
I reinstalled my version locally using `cargo install git-cm --force` and then deleted the directory you mentioned. My executable does keep working though.

**Comment by NOBLES5E** [comment]
I just setup a clean github workflow to declaratively reproduce the bug, see [here](https://github.com/NOBLES5E/git-cm-bug-report/runs/2432829157?check_suite_focus=true) and [code](https://github.com/NOBLES5E/git-cm-bug-report/blob/master/.github/workflows/trigger-bug.yml). Feel free to fork it.

Note that there needs to be something to commit to trigger this bug (for example doing a `echo 123 > test && git add test`) in your local repo and then running `git-cm`.

**Comment by SirWindfield** [comment]
Found it: https://github.com/SirWindfield/git-cm/blob/f298f98607afdaf575e9e47980d3a8ead4042f4c/src/cargo.rs#L25. `env!` IIRC embeds at compile time.

**Comment by NOBLES5E** [comment]
Thanks!

> Mind opening a PR to fix this?

Sure

**Comment by NOBLES5E** [comment]
@SirWindfield Mind creating a new release?

**Comment by SirWindfield** [comment]
I'll take time on Saturday and merge the PR as well!

**Comment by SirWindfield** [comment]
Sorry that it took that long. v0.2.3 is out. You can use crates or download from my homebrew tap: `brew install sirwindfield/tap/git-cm`. Thanks for the fix!
